# config/packages/translation.yaml

framework:
    default_locale: fr

    enabled_locales:
        - bg # Bulgare
        - hr # Croate
        - cs # Tchèque
        - da # Danois
        - nl # Néerlandais
        - en # Anglais
        - et # Estonien
        - fi # Finnois
        - fr # Français
        - de # Allemand
        - el # Grec
        - hu # Hongrois
        - ga # Irlandais
        - it # Italien
        - lv # Letton
        - lt # Lituanien
        - mt # Maltais
        - pl # Polonais
        - pt # Portugais
        - ro # Roumain
        - sk # Slovaque
        - sl # Slovène
        - es # Espagnol
        - sv # Suédois

    translator:
        default_path: '%kernel.project_dir%/translations'

        fallbacks:
            - fr

        providers: {}