<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260620212855 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE plan_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, currency VARCHAR(3) NOT NULL, amount_cents INT NOT NULL, billing_interval VARCHAR(20) NOT NULL, trial_period_days INT DEFAULT NULL, stripe_price_id VARCHAR(120) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, plan_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_996E6725989D9B62 ON plan_price (slug)');
        $this->addSql('CREATE INDEX IDX_996E6725E899029B ON plan_price (plan_id)');
        $this->addSql('ALTER TABLE plan_price ADD CONSTRAINT FK_996E6725E899029B FOREIGN KEY (plan_id) REFERENCES subscription_plan (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE plan_price DROP CONSTRAINT FK_996E6725E899029B');
        $this->addSql('DROP TABLE plan_price');
    }
}
