<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWP5EU2E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWP5EU2E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWP5EU2E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWP5EU2E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWP5EU2E\App_KernelDevDebugContainer([
    'container.build_hash' => 'WP5EU2E',
    'container.build_id' => '16be1b39',
    'container.build_time' => 1782024062,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWP5EU2E');
